"""Generated from DAL OpenAPI x-jql metadata; do not edit."""

from typing import Literal

JQL_IR_SCHEMA_SHA256 = (
    "6ae52ed9a91fe26af4c56007e041b57b6e7b0d474f493a555e7327c556567c76"
)
SUPPORTED_OPS = (
    "agg",
    "agg_expr",
    "all",
    "ancestor_of",
    "any",
    "any_span",
    "any_trace",
    "arith",
    "at_least",
    "attr",
    "bucket",
    "chart",
    "cited_by",
    "col",
    "cost",
    "count",
    "derive",
    "descendant_of",
    "discovery",
    "duration",
    "eq",
    "every_span",
    "every_trace",
    "grep",
    "gt",
    "gte",
    "ids",
    "judge",
    "judged",
    "lt",
    "lte",
    "model",
    "name",
    "ne",
    "no_span",
    "no_trace",
    "not",
    "over_scores",
    "over_spans",
    "over_traces",
    "pick",
    "query",
    "ranked",
    "recent",
    "rg",
    "rows",
    "sort",
    "status",
    "summarize",
    "table",
    "take",
    "tokens",
    "top",
    "trend",
    "where",
)
DiscoveryKind = Literal[
    "judges",
    "behaviors",
    "span_names",
    "models",
    "fields",
    "rules",
    "judge_prompts",
    "judge_config",
    "citations",
]
