# Auto-generated by scripts/api_generator_v1.py
# DO NOT EDIT MANUALLY
from __future__ import annotations

from typing import TypedDict, Optional, List, Any, Dict
from typing_extensions import NotRequired


class CreateTestRunRequest(TypedDict):
    test_config_id: str
    dataset_version_id: NotRequired[Optional[str]]
    dataset_version_number: NotRequired[Optional[float]]
    judge_versions: NotRequired[Optional[List[Dict[str, Any]]]]
    source: NotRequired[Optional[str]]
    versioned_results: NotRequired[Optional[bool]]
