# Auto-generated by scripts/api_generator_v1.py
# DO NOT EDIT MANUALLY
from __future__ import annotations

from typing import TypedDict, Optional, Any, Dict
from typing_extensions import NotRequired


class CreateExternalJudgeInput(TypedDict):
    name: str
    judgeDescription: NotRequired[Optional[str]]
    judgeType: str
    config: NotRequired[Optional[Dict[str, Any]]]
    initialVersion: Dict[str, Any]
