name: Lint

on:
  pull_request:
    branches: [ main, staging ]
  push:
    branches: [justin/mypy-fix]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install uv
          uv sync --dev

      - name: Install ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "--version"

      - name: Run ruff formatter
        if: always()
        run: ruff format --check .

      - name: Run ruff linter
        if: always()
        run: ruff check .

      - name: Run mypy
        if: always()
        continue-on-error: true # TODO: remove this once all mypy errors are fixed
        run: uv run mypy ./src/judgeval/